name: Deploy to S3

on:
  push:
    branches:
      - main  # Cambia esto a la rama que estés usando para producción

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1  # Cambia esto a la región de tu bucket

      - name: Sync S3 Bucket
        run: |
          aws s3 sync ./dist/ s3://tu-bucket-s3 --delete
